"""ストップワード定義.

日本語と英語のストップワードを定義するモジュール。
テキスト解析やNLP処理で不要な語を除外するために使用。
"""

# 日本語ストップワード（Japanese Stop Words）
JP_STOP_WORDS = {
    # 助詞（Particles）
    "助詞": [
        # 格助詞
        "が",
        "の",
        "を",
        "に",
        "へ",
        "と",
        "から",
        "より",
        "で",
        # 並立助詞
        "や",
        "と",
        "たり",
        "だり",
        "なり",
        "やら",
        # 接続助詞
        "て",
        "で",
        "ながら",
        "つつ",
        "ので",
        "のに",
        "ば",
        "たら",
        "と",
        # 副助詞
        "は",
        "も",
        "こそ",
        "さえ",
        "でも",
        "しか",
        "まで",
        "だけ",
        "ばかり",
        "など",
        "くらい",
        # 終助詞
        "ね",
        "よ",
        "な",
        "かな",
        "わ",
        "ぞ",
        "ぜ",
        "っけ",
        "さ",
        # 係助詞
        "は",
        "も",
        "こそ",
        "でも",
        "しか",
        "さえ",
        "だに",
        # 追加の格助詞
        "にて",
        "において",
        "について",
        "により",
        "による",
        "によって",
        # 追加の副助詞
        "ほど",
        "がてら",
        "かしら",
        "なんて",
        "だって",
    ],
    # 助動詞（Auxiliary Verbs）
    "助動詞": [
        # 丁寧
        "です",
        "ます",
        "でした",
        "ました",
        "でしょう",
        "ましょう",
        "でございます",
        "でございました",
        # 受身・使役
        "れる",
        "られる",
        "せる",
        "させる",
        "しめる",
        # 否定
        "ない",
        "ぬ",
        "ん",
        "まい",
        "なかった",
        "ません",
        # 推量・様態
        "そうだ",
        "ようだ",
        "らしい",
        "かもしれない",
        "にちがいない",
        "みたいだ",
        "っぽい",
        "はずだ",
        "べきだ",
        # 追加の助動詞
        "たい",
        "だろう",
        "でしょう",
        "らしい",
        "ようです",
        "そうです",
        "なさい",
        "ください",
        "たがる",
        "かねる",
        "がたい",
    ],
    # 代名詞（Pronouns）
    "代名詞": [
        # 人称代名詞
        "私",
        "わたし",
        "僕",
        "ぼく",
        "俺",
        "おれ",
        "あたし",
        "あなた",
        "君",
        "きみ",
        "お前",
        "おまえ",
        "彼",
        "かれ",
        "彼女",
        "かのじょ",
        "我々",
        "われわれ",
        "私たち",
        "わたしたち",
        "僕たち",
        "ぼくたち",
        # 指示代名詞
        "これ",
        "それ",
        "あれ",
        "どれ",
        "この",
        "その",
        "あの",
        "どの",
        "ここ",
        "そこ",
        "あそこ",
        "どこ",
        "こちら",
        "そちら",
        "あちら",
        "どちら",
        # 不定代名詞
        "なに",
        "何",
        "だれ",
        "誰",
        "いつ",
        "どう",
        "どんな",
        # 追加の代名詞
        "自分",
        "みんな",
        "皆",
        "だれか",
        "誰か",
        "なにか",
        "何か",
        "どなた",
        "どちらさま",
        "どいつ",
        "そいつ",
        "あいつ",
    ],
    # 接続詞（Conjunctions）
    "接続詞": [
        "そして",
        "および",
        "かつ",
        "または",
        "もしくは",
        "けれども",
        "しかし",
        "ただし",
        "なお",
        "また",
        "さらに",
        "なぜなら",
        "したがって",
        "それで",
        "それでは",
        "すなわち",
        "つまり",
        # 追加の接続詞
        "ところが",
        "それとも",
        "あるいは",
        "ゆえに",
        "だから",
        "というのは",
        "というのも",
        "ですが",
        "ところで",
        "さて",
        "ただ",
        "でも",
        "しかも",
        "それに",
        "おまけに",
    ],
    # 感動詞（Interjections）
    "感動詞": [
        "あ",
        "あっ",
        "ああ",
        "はい",
        "いいえ",
        "えっ",
        "おい",
        "やあ",
        "いやあ",
        "おや",
        "まあ",
        "なるほど",
        "へえ",
        "うん",
        "ううん",
        "あの",
        "その",
        "えーと",
        "えっと",
    ],
}

# 英語ストップワード（English Stop Words）
EN_STOP_WORDS = {
    # 冠詞（Articles）
    "articles": [
        "a",
        "an",
        "the",
    ],
    # 代名詞（Pronouns）
    "pronouns": [
        # 人称代名詞
        "i",
        "you",
        "he",
        "she",
        "it",
        "we",
        "they",
        "me",
        "him",
        "her",
        "us",
        "them",
        "my",
        "your",
        "his",
        "her",
        "its",
        "our",
        "their",
        "mine",
        "yours",
        "his",
        "hers",
        "its",
        "ours",
        "theirs",
        # 指示代名詞
        "this",
        "that",
        "these",
        "those",
        # 関係代名詞
        "who",
        "whom",
        "whose",
        "which",
        "what",
        # 不定代名詞
        "anybody",
        "anyone",
        "anything",
        "everybody",
        "everyone",
        "everything",
        "nobody",
        "no one",
        "nothing",
        "somebody",
        "someone",
        "something",
        # 追加の代名詞
        "myself",
        "yourself",
        "himself",
        "herself",
        "itself",
        "ourselves",
        "yourselves",
        "themselves",
        "each other",
        "one another",
    ],
    # 前置詞（Prepositions）
    "prepositions": [
        "in",
        "on",
        "at",
        "to",
        "for",
        "of",
        "with",
        "by",
        "from",
        "about",
        "into",
        "through",
        "after",
        "over",
        "between",
        "out",
        "against",
        "during",
        "without",
        "within",
        "throughout",
        "behind",
        "beyond",
        "beside",
        "besides",
        "among",
        "across",
        "along",
        "around",
        "despite",
        "under",
        "underneath",
        "upon",
        # 追加の前置詞
        "amid",
        "amidst",
        "amongst",
        "below",
        "beneath",
        "inside",
        "outside",
        "via",
        "versus",
        "per",
        "unlike",
        "like",
        "except",
        "concerning",
        "regarding",
        "considering",
    ],
    # 接続詞（Conjunctions）
    "conjunctions": [
        "and",
        "or",
        "but",
        "if",
        "when",
        "while",
        "because",
        "although",
        "unless",
        "since",
        "where",
        "whether",
        "before",
        "after",
        "as",
        "though",
        "even though",
        "whereas",
        "so",
        "therefore",
        "hence",
        "thus",
        "moreover",
        "furthermore",
        # 追加の接続詞
        "yet",
        "still",
        "however",
        "nevertheless",
        "nonetheless",
        "meanwhile",
        "consequently",
        "accordingly",
        "besides",
        "alternatively",
        "conversely",
        "instead",
        "otherwise",
    ],
    # 助動詞（Auxiliary Verbs）
    "auxiliaries": [
        "am",
        "is",
        "are",
        "was",
        "were",
        "be",
        "been",
        "being",
        "have",
        "has",
        "had",
        "do",
        "does",
        "did",
        "will",
        "would",
        "shall",
        "should",
        "can",
        "could",
        "may",
        "might",
        "must",
        "ought",
        "need",
        "dare",
        "used to",
        "going to",
        # 追加の助動詞
        "let",
        "lets",
        "ought to",
        "had better",
        "would rather",
        "would like",
        "would prefer",
        "might have",
        "could have",
        "should have",
        "must have",
        "cannot",
        "can't",
        "won't",
    ],
    # 一般的な動詞（Common Verbs）
    "common_verbs": [
        "get",
        "got",
        "getting",
        "make",
        "made",
        "making",
        "go",
        "went",
        "gone",
        "going",
        "come",
        "came",
        "coming",
        "take",
        "took",
        "taken",
        "taking",
        "give",
        "gave",
        "given",
        "giving",
        "know",
        "knew",
        "known",
        "knowing",
        # 追加の一般動詞
        "say",
        "said",
        "saying",
        "see",
        "saw",
        "seen",
        "seeing",
        "think",
        "thought",
        "thinking",
        "want",
        "wanted",
        "wanting",
        "look",
        "looked",
        "looking",
        "use",
        "used",
        "using",
        "find",
        "found",
        "finding",
        "need",
        "needed",
        "needing",
    ],
    # 一般的な形容詞（Common Adjectives）
    "common_adjectives": [
        "good",
        "bad",
        "big",
        "small",
        "high",
        "low",
        "old",
        "new",
        "first",
        "last",
        "long",
        "short",
        "own",
        "right",
        "wrong",
        "true",
        "false",
        "same",
        "different",
        "other",
        "next",
    ],
    # 一般的な副詞（Common Adverbs）
    "common_adverbs": [
        "very",
        "really",
        "quite",
        "just",
        "now",
        "then",
        "here",
        "there",
        "today",
        "tomorrow",
        "yesterday",
        "always",
        "never",
        "sometimes",
        "often",
        "usually",
        "already",
        "still",
        "too",
    ],
}
